project:
  type: book
  output-dir: _book

book:
  title: "My book"
  author: "Lingyun Zhang"
  date: today
  date-format: YYYY-MM-DD
  chapters:
    - index.qmd

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]

editor: visual

